version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development # Use the development stage for dev environment
    ports:
      - "0.0.0.0:5173:5173" # Expose Vite's default port
    volumes:
      - ./client:/app # Mount client directory for live reload
      - /app/node_modules # Exclude node_modules from host to use container's version
      # No /app/dist volume needed for Vite dev server
    networks:
      - deployio-network
    # No command override needed, Dockerfile's CMD for Vite dev server will be used.

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./server/.env.dev
    volumes:
      - ./server:/app # Mounts the server directory for development
      - /app/node_modules # Excludes node_modules from being overwritten
    command: npm run server # Use nodemon via npm script
    depends_on:
      - mongo
    networks:
      - deployio-network

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./service/.env.dev
    depends_on:
      - mongo
    networks:
      - deployio-network
    volumes:
      - ./service:/app # Mounts the service directory for development
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # Changed host to 0.0.0.0

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - deployio-network

networks:
  deployio-network:
    driver: bridge

volumes:
  mongo-data:
