import { useState, useEffect, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  FiX,
  FiSave,
  FiCode,
  FiEye,
  FiZap,
  FiAlertCircle,
  FiCheckCircle,
  FiCircle,
  FiCopy,
  FiDownload,
} from "react-icons/fi";

const CodeEditor = ({ workspace, setWorkspace, aiState, setAiState }) => {
  const [code, setCode] = useState("");
  const [isEditing, setIsEditing] = useState(false);
  const [suggestions, setSuggestions] = useState([]);
  const [showPreview, setShowPreview] = useState(false);
  const [editorSettings] = useState({
    theme: "dark",
    fontSize: 14,
    tabSize: 2,
    wordWrap: true,
    minimap: true,
    autoSave: true,
  });
  const textareaRef = useRef(null);

  // Sample code for different file types
  const sampleCode = {
    "app.js": `// Node.js Express Application
const express = require('express');
const app = express();
const port = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.static('public'));

// Routes
app.get('/', (req, res) => {
  res.json({ 
    message: 'Welcome to DeployIO Playground!',
    version: '1.0.0',
    environment: process.env.NODE_ENV || 'development'
  });
});

app.get('/health', (req, res) => {
  res.status(200).json({ 
    status: 'healthy',
    timestamp: new Date().toISOString()
  });
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

app.listen(port, () => {
  console.log(\`Server running on port \${port}\`);
});

module.exports = app;`,
    Dockerfile: `# Multi-stage Docker build for Node.js application
# Generated by DeployIO AI

# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production && npm cache clean --force

# Copy source code
COPY . .

# Production stage
FROM node:18-alpine AS production

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S deployio -u 1001

WORKDIR /app

# Copy from builder stage
COPY --from=builder --chown=deployio:nodejs /app .

# Security: Remove unnecessary packages
RUN apk del --purge

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD node healthcheck.js

# Switch to non-root user
USER deployio

# Start application
CMD ["node", "app.js"]`,
    "docker-compose.yml": `# Docker Compose configuration
# Generated by DeployIO AI
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: deployio
      POSTGRES_USER: deployio
      POSTGRES_PASSWORD: \${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    driver: bridge`,
    "ci.yml": `# GitHub Actions CI/CD Pipeline
# Generated by DeployIO AI
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: \${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: \${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run tests
      run: npm test
      env:
        CI: true
    
    - name: Run security audit
      run: npm audit --production

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: \${{ env.REGISTRY }}
        username: \${{ github.actor }}
        password: \${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add deployment script here`,
  };

  // Load file content when active file changes
  useEffect(() => {
    if (workspace.activeFile && sampleCode[workspace.activeFile]) {
      setCode(sampleCode[workspace.activeFile]);
    } else if (workspace.activeFile) {
      setCode(`// ${workspace.activeFile}\n// Start coding here...\n`);
    }
  }, [workspace.activeFile]);

  const handleSave = useCallback(() => {
    setIsEditing(false);
    if (workspace.activeFile) {
      setWorkspace((prev) => {
        const newUnsaved = new Set(prev.unsavedChanges);
        newUnsaved.delete(workspace.activeFile);
        return {
          ...prev,
          unsavedChanges: newUnsaved,
        };
      });
    }
  }, [workspace.activeFile, setWorkspace]);

  // Auto-save functionality
  useEffect(() => {
    if (editorSettings.autoSave && isEditing) {
      const timer = setTimeout(() => {
        handleSave();
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [code, isEditing, editorSettings.autoSave, handleSave]);

  const handleCodeChange = (value) => {
    setCode(value);
    setIsEditing(true);

    // Mark file as having unsaved changes
    if (workspace.activeFile) {
      setWorkspace((prev) => ({
        ...prev,
        unsavedChanges: new Set([...prev.unsavedChanges, workspace.activeFile]),
      }));
    }

    // Trigger AI analysis for suggestions
    if (aiState.isAnalyzing) return;

    const timer = setTimeout(() => {
      analyzeCode(value);
    }, 1000);

    return () => clearTimeout(timer);
  };

  const analyzeCode = async (_codeContent) => {
    setAiState((prev) => ({ ...prev, isAnalyzing: true }));

    // Simulate AI analysis
    setTimeout(() => {
      const newSuggestions = [
        {
          line: 5,
          type: "optimization",
          message: "Consider using async/await for better error handling",
          severity: "info",
        },
        {
          line: 12,
          type: "security",
          message: "Add input validation for this endpoint",
          severity: "warning",
        },
        {
          line: 20,
          type: "performance",
          message: "This operation could be optimized with caching",
          severity: "info",
        },
      ];

      setSuggestions(newSuggestions);
      setAiState((prev) => ({
        ...prev,
        isAnalyzing: false,
        suggestions: newSuggestions,
      }));
    }, 2000);
  };
  const handleCloseFile = (fileName) => {
    setWorkspace((prev) => ({
      ...prev,
      openFiles: prev.openFiles.filter((f) => f !== fileName),
      activeFile:
        prev.activeFile === fileName
          ? prev.openFiles.find((f) => f !== fileName) || null
          : prev.activeFile,
    }));
  };

  const getFileLanguage = (fileName) => {
    const ext = fileName.split(".").pop();
    switch (ext) {
      case "js":
        return "javascript";
      case "json":
        return "json";
      case "yml":
      case "yaml":
        return "yaml";
      case "md":
        return "markdown";
      default:
        return "text";
    }
  };

  const getLineNumbers = () => {
    const lines = code.split("\n").length;
    return Array.from({ length: lines }, (_, i) => i + 1);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(code);
  };

  const downloadFile = () => {
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = workspace.activeFile || "code.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!workspace.activeFile) {
    return (
      <div className="h-full flex items-center justify-center bg-neutral-950/50">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center"
        >
          <FiCode className="w-16 h-16 text-gray-600 mx-auto mb-4" />
          <h3 className="text-xl font-medium text-gray-400 mb-2">
            No file selected
          </h3>
          <p className="text-gray-500">
            Select a file from the explorer to start coding
          </p>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-neutral-950/50">
      {/* File Tabs */}
      <div className="flex items-center bg-neutral-900/60 border-b border-neutral-800/50">
        <div className="flex items-center overflow-x-auto">
          {workspace.openFiles.map((fileName) => {
            const isActive = workspace.activeFile === fileName;
            const hasUnsaved = workspace.unsavedChanges.has(fileName);

            return (
              <motion.div
                key={fileName}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className={`
                  flex items-center gap-2 px-4 py-2 border-r border-neutral-800/50 cursor-pointer
                  ${
                    isActive
                      ? "bg-neutral-950/50 text-white"
                      : "text-gray-400 hover:text-white hover:bg-neutral-800/30"
                  }
                  transition-colors
                `}
                onClick={() =>
                  setWorkspace((prev) => ({ ...prev, activeFile: fileName }))
                }
              >
                <span className="text-sm">{fileName}</span>
                {hasUnsaved && (
                  <FiCircle className="w-2 h-2 text-yellow-400 fill-current" />
                )}
                <motion.button
                  whileHover={{ scale: 1.2 }}
                  whileTap={{ scale: 0.8 }}
                  onClick={(e) => {
                    e.stopPropagation();
                    handleCloseFile(fileName);
                  }}
                  className="text-gray-500 hover:text-gray-300"
                >
                  <FiX className="w-3 h-3" />
                </motion.button>
              </motion.div>
            );
          })}
        </div>

        {/* Editor Actions */}
        <div className="ml-auto flex items-center gap-2 px-4">
          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={copyToClipboard}
            className="p-1.5 rounded-md hover:bg-neutral-800/50 text-gray-400 hover:text-white transition-colors"
            title="Copy to clipboard"
          >
            <FiCopy className="w-4 h-4" />
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={downloadFile}
            className="p-1.5 rounded-md hover:bg-neutral-800/50 text-gray-400 hover:text-white transition-colors"
            title="Download file"
          >
            <FiDownload className="w-4 h-4" />
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={() => setShowPreview(!showPreview)}
            className={`p-1.5 rounded-md transition-colors ${
              showPreview
                ? "bg-blue-500/20 text-blue-400"
                : "hover:bg-neutral-800/50 text-gray-400 hover:text-white"
            }`}
            title="Toggle preview"
          >
            <FiEye className="w-4 h-4" />
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={handleSave}
            className={`p-1.5 rounded-md transition-colors ${
              isEditing ? "bg-green-500/20 text-green-400" : "text-gray-400"
            }`}
            title="Save file"
          >
            <FiSave className="w-4 h-4" />
          </motion.button>
        </div>
      </div>

      {/* Editor Container */}
      <div className="flex-1 flex">
        {/* Code Editor */}
        <div className="flex-1 flex">
          {/* Line Numbers */}
          <div className="w-12 bg-neutral-900/30 border-r border-neutral-800/50 py-4 text-right pr-2">
            {getLineNumbers().map((num) => (
              <div key={num} className="text-xs text-gray-500 h-5 leading-5">
                {num}
              </div>
            ))}
          </div>

          {/* Code Area */}
          <div className="flex-1 relative">
            <textarea
              ref={textareaRef}
              value={code}
              onChange={(e) => handleCodeChange(e.target.value)}
              className="w-full h-full p-4 bg-transparent text-white font-mono text-sm leading-5 resize-none outline-none"
              style={{ fontSize: editorSettings.fontSize }}
              placeholder="Start typing your code..."
              spellCheck={false}
            />

            {/* Syntax Highlighting Overlay */}
            <div className="absolute inset-0 pointer-events-none p-4 font-mono text-sm leading-5 overflow-hidden">
              {/* This would be replaced with proper syntax highlighting */}
            </div>

            {/* AI Suggestions Overlay */}
            <AnimatePresence>
              {suggestions.map((suggestion, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20 }}
                  className="absolute right-4 bg-neutral-800/90 backdrop-blur-sm border border-neutral-700 rounded-md p-2 text-xs max-w-xs"
                  style={{ top: `${suggestion.line * 20 + 60}px` }}
                >
                  <div className="flex items-center gap-2 mb-1">
                    {suggestion.severity === "warning" ? (
                      <FiAlertCircle className="w-3 h-3 text-yellow-400" />
                    ) : (
                      <FiCheckCircle className="w-3 h-3 text-blue-400" />
                    )}
                    <span className="font-medium text-white capitalize">
                      {suggestion.type}
                    </span>
                  </div>
                  <p className="text-gray-300">{suggestion.message}</p>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </div>

        {/* Preview Panel */}
        <AnimatePresence>
          {showPreview && (
            <motion.div
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: "50%", opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              className="border-l border-neutral-800/50 bg-neutral-900/30"
            >
              <div className="p-4">
                <h3 className="text-sm font-medium text-white mb-3">Preview</h3>
                <div className="text-sm text-gray-300">
                  {getFileLanguage(workspace.activeFile) === "markdown" ? (
                    <div
                      dangerouslySetInnerHTML={{
                        __html: code.replace(/\n/g, "<br>"),
                      }}
                    />
                  ) : (
                    <pre className="whitespace-pre-wrap">{code}</pre>
                  )}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Status Bar */}
      <div className="h-6 bg-neutral-900/80 border-t border-neutral-800/50 flex items-center justify-between px-4 text-xs text-gray-400">
        <div className="flex items-center gap-4">
          <span>Line {code.split("\n").length}</span>
          <span>Language: {getFileLanguage(workspace.activeFile)}</span>
          {aiState.isAnalyzing && (
            <div className="flex items-center gap-2">
              <FiZap className="w-3 h-3 text-yellow-400 animate-pulse" />
              <span className="text-yellow-400">AI Analyzing...</span>
            </div>
          )}
        </div>
        <div className="flex items-center gap-4">
          <span>UTF-8</span>
          <span>Spaces: {editorSettings.tabSize}</span>
          {isEditing && <span className="text-yellow-400">Unsaved</span>}
        </div>
      </div>
    </div>
  );
};

export default CodeEditor;
