import { useState, useCallback, useMemo } from "react";
import { motion } from "framer-motion";
import {
  FiX,
  FiCode,
  FiCheckCircle,
  FiCopy,
  FiLock,
  FiFile,
} from "react-icons/fi";
import { FaCode, FaLock } from "react-icons/fa";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";

// Helper function to determine language from filename
const getLanguageFromFilename = (filename) => {
  const ext = filename?.split(".").pop()?.toLowerCase();
  const languageMap = {
    js: "javascript",
    jsx: "jsx",
    ts: "typescript",
    tsx: "tsx",
    py: "python",
    html: "html",
    css: "css",
    scss: "scss",
    sass: "sass",
    json: "json",
    xml: "xml",
    yaml: "yaml",
    yml: "yaml",
    md: "markdown",
    dockerfile: "dockerfile",
    sh: "bash",
    bash: "bash",
    sql: "sql",
    php: "php",
    java: "java",
    c: "c",
    cpp: "cpp",
    go: "go",
    rs: "rust",
    rb: "ruby",
    swift: "swift",
    kt: "kotlin",
  };

  // Special case for Dockerfile
  if (filename?.toLowerCase() === "dockerfile") {
    return "dockerfile";
  }

  return languageMap[ext] || "text";
};

// TODO: Implement GitHub integration for fetching repository files
// Repository: vasudevshetty/mern, branch: main
// This function will fetch file content from GitHub using a client-side token
const fetchGitHubRepositoryFiles = async (
  token,
  owner = "vasudevshetty",
  repo = "mern",
  branch = "main"
) => {
  try {
    // TODO: Implement GitHub API integration
    // 1. Fetch repository tree structure using GitHub API
    // 2. Get file contents for supported file types
    // 3. Transform file structure for use in file explorer
    // 4. Cache results to avoid API rate limiting

    const apiUrl = `https://api.github.com/repos/${owner}/${repo}/git/trees/${branch}?recursive=1`;

    const response = await fetch(apiUrl, {
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github.v3+json",
      },
    });

    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }

    const data = await response.json();

    // TODO: Process tree data and fetch individual file contents
    // Filter for supported file types and organize into folder structure
    console.log("GitHub repository data:", data);

    return data;
  } catch (error) {
    console.error("Error fetching GitHub repository:", error);
    throw error;
  }
};

// TODO: Add function to fetch individual file content from GitHub
const fetchGitHubFileContent = async (
  token,
  owner,
  repo,
  path,
  branch = "main"
) => {
  try {
    const apiUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${branch}`;

    const response = await fetch(apiUrl, {
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github.v3+json",
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch file: ${response.status}`);
    }

    const data = await response.json();

    // Decode base64 content
    return atob(data.content);
  } catch (error) {
    console.error("Error fetching file content:", error);
    throw error;
  }
};

const CodeEditor = ({ setWorkspace, onFileSelect, isFileEditable }) => {
  const [activeFile, setActiveFile] = useState(null);
  const [openFiles, setOpenFiles] = useState([]);

  // Sample code for different file types - memoized to prevent re-renders
  const sampleCode = useMemo(
    () => ({
      "app.js": `// Node.js Express Application
const express = require('express');
const app = express();
const port = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.static('public'));

// Routes
app.get('/', (req, res) => {
  res.json({ 
    message: 'Welcome to Deployio Playground!',
    version: '1.0.0',
    environment: process.env.NODE_ENV || 'development'
  });
});

app.get('/health', (req, res) => {
  res.status(200).json({ 
    status: 'healthy',
    timestamp: new Date().toISOString()
  });
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

app.listen(port, () => {
  console.log(\`Server running on port \${port}\`);
});

module.exports = app;`,

      Dockerfile: `# Multi-stage Docker build for Node.js application
# Generated by Deployio AI

# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production && npm cache clean --force

# Copy source code
COPY . .

# Production stage
FROM node:18-alpine AS production

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S deployio -u 1001

WORKDIR /app

# Copy from builder stage
COPY --from=builder --chown=deployio:nodejs /app .

# Security: Remove unnecessary packages
RUN apk del --purge

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD node healthcheck.js

# Switch to non-root user
USER deployio

# Start application
CMD ["node", "app.js"]`,

      "docker-compose.yml": `# Docker Compose configuration
# Generated by Deployio AI
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: deployio
      POSTGRES_USER: deployio
      POSTGRES_PASSWORD: \${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:`,
    }),
    []
  );

  // Handle file selection
  const handleFileSelect = useCallback(
    (filePath, content) => {
      const newFile = {
        path: filePath,
        content: content || sampleCode[filePath] || "// File content",
        editable: !isFileEditable(filePath),
      };

      setActiveFile(newFile);

      // Add to open files if not already open
      if (!openFiles.find((f) => f.path === filePath)) {
        setOpenFiles((prev) => [...prev, newFile]);
      }

      // Update workspace
      setWorkspace((prev) => ({
        ...prev,
        activeFile: newFile,
      }));

      // Call parent handler
      if (onFileSelect) {
        onFileSelect(filePath);
      }
    },
    [openFiles, isFileEditable, setWorkspace, onFileSelect, sampleCode]
  );

  // Close file tab
  const closeFile = (filePath) => {
    setOpenFiles((prev) => prev.filter((f) => f.path !== filePath));
    if (activeFile?.path === filePath) {
      const remainingFiles = openFiles.filter((f) => f.path !== filePath);
      if (remainingFiles.length > 0) {
        setActiveFile(remainingFiles[remainingFiles.length - 1]);
      } else {
        setActiveFile(null);
      }
    }
  };

  // Copy content to clipboard
  const copyToClipboard = async () => {
    if (activeFile?.content) {
      try {
        await navigator.clipboard.writeText(activeFile.content);
        // Could add toast notification here
      } catch (err) {
        console.error("Failed to copy:", err);
      }
    }
  };

  return (
    <div className="h-full flex flex-col bg-neutral-900">
      {/* Tab Bar */}
      <div className="flex items-center bg-neutral-950 border-b border-neutral-800/50 min-h-[40px]">
        <div className="flex-1 flex items-center overflow-x-auto custom-scrollbar">
          {openFiles.map((file) => (
            <motion.div
              key={file.path}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className={`flex items-center gap-2 px-3 py-2 border-r border-neutral-800/50 cursor-pointer transition-colors ${
                activeFile?.path === file.path
                  ? "bg-neutral-900 text-white"
                  : "text-neutral-400 hover:text-white hover:bg-neutral-800/50"
              }`}
              onClick={() => setActiveFile(file)}
            >
              <FiFile className="w-3 h-3 flex-shrink-0" />
              <span className="text-sm body">{file.path.split("/").pop()}</span>
              {!file.editable && (
                <FaLock className="w-3 h-3 text-red-400 flex-shrink-0" />
              )}
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  closeFile(file.path);
                }}
                className="w-4 h-4 flex items-center justify-center rounded hover:bg-neutral-700 transition-colors"
              >
                <FiX className="w-3 h-3" />
              </button>
            </motion.div>
          ))}
        </div>

        {/* Editor Actions */}
        {activeFile && (
          <div className="flex items-center gap-1 px-2">
            <motion.button
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              onClick={copyToClipboard}
              className="p-1.5 rounded hover:bg-neutral-800 transition-colors text-neutral-400 hover:text-white"
              title="Copy to Clipboard"
            >
              <FiCopy className="w-3.5 h-3.5" />
            </motion.button>
          </div>
        )}
      </div>

      {/* Editor Content */}
      <div className="flex-1 flex">
        {activeFile ? (
          <div className="flex-1 relative">
            {/* File Status Bar */}
            <div className="absolute top-0 right-0 z-10 bg-neutral-950/90 backdrop-blur-sm border border-neutral-800/50 rounded-bl px-3 py-1 flex items-center gap-2">
              {activeFile.editable ? (
                <>
                  <FiCheckCircle className="w-3 h-3 text-green-400" />
                  <span className="text-xs text-green-400 body">Editable</span>
                </>
              ) : (
                <>
                  <FiLock className="w-3 h-3 text-red-400" />
                  <span className="text-xs text-red-400 body">Read-only</span>
                </>
              )}
            </div>

            {/* Code Display */}
            <div className="h-full overflow-auto custom-scrollbar">
              <SyntaxHighlighter
                language={getLanguageFromFilename(activeFile.name)}
                style={vscDarkPlus}
                customStyle={{
                  margin: 0,
                  padding: "1rem",
                  background: "transparent",
                  fontSize: "0.875rem",
                  lineHeight: "1.5",
                  fontFamily:
                    'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
                }}
                wrapLines={true}
                wrapLongLines={true}
                showLineNumbers={true}
                lineNumberStyle={{
                  color: "#6b7280",
                  paddingRight: "1rem",
                  fontSize: "0.75rem",
                }}
              >
                {activeFile.content}
              </SyntaxHighlighter>
            </div>
          </div>
        ) : (
          /* Welcome Screen - VSCode Inspired */
          <div className="flex-1 flex items-center justify-center bg-neutral-900">
            <div className="text-center max-w-lg px-8">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-8"
              >
                <div className="w-20 h-20 mx-auto mb-6 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                  <FaCode className="w-10 h-10 text-white" />
                </div>
                <h1 className="text-2xl font-bold text-white mb-3 heading">
                  Deployio Playground
                </h1>
                <p className="text-neutral-400 body leading-relaxed text-lg">
                  Explore DevOps configurations and best practices with our
                  AI-powered code editor.
                </p>
              </motion.div>

              {/* Start Actions */}
              <div className="space-y-3 mb-8">
                <div className="text-sm font-semibold text-neutral-300 mb-3 heading uppercase tracking-wide">
                  Start
                </div>
                <motion.button
                  whileHover={{ scale: 1.01, x: 4 }}
                  whileTap={{ scale: 0.99 }}
                  onClick={() => handleFileSelect("Dockerfile")}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-neutral-800/50 rounded-lg transition-all group"
                >
                  <div className="w-8 h-8 bg-blue-500/20 rounded flex items-center justify-center group-hover:bg-blue-500/30 transition-colors">
                    <FiCode className="w-4 h-4 text-blue-400" />
                  </div>
                  <div>
                    <div className="text-white font-medium body">
                      Open Dockerfile
                    </div>
                    <div className="text-xs text-neutral-500">
                      Docker containerization setup
                    </div>
                  </div>
                </motion.button>

                <motion.button
                  whileHover={{ scale: 1.01, x: 4 }}
                  whileTap={{ scale: 0.99 }}
                  onClick={() => handleFileSelect("docker-compose.yml")}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-neutral-800/50 rounded-lg transition-all group"
                >
                  <div className="w-8 h-8 bg-green-500/20 rounded flex items-center justify-center group-hover:bg-green-500/30 transition-colors">
                    <FiFile className="w-4 h-4 text-green-400" />
                  </div>
                  <div>
                    <div className="text-white font-medium body">
                      Open Docker Compose
                    </div>
                    <div className="text-xs text-neutral-500">
                      Multi-container application setup
                    </div>
                  </div>
                </motion.button>

                <motion.button
                  whileHover={{ scale: 1.01, x: 4 }}
                  whileTap={{ scale: 0.99 }}
                  onClick={() => handleFileSelect("app.js")}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-neutral-800/50 rounded-lg transition-all group"
                >
                  <div className="w-8 h-8 bg-yellow-500/20 rounded flex items-center justify-center group-hover:bg-yellow-500/30 transition-colors">
                    <FiCode className="w-4 h-4 text-yellow-400" />
                  </div>
                  <div>
                    <div className="text-white font-medium body">
                      Open Node.js App
                    </div>
                    <div className="text-xs text-neutral-500">
                      Sample Express.js application
                    </div>
                  </div>
                </motion.button>
              </div>

              {/* Recent */}
              <div className="text-left">
                <div className="text-sm font-semibold text-neutral-300 mb-3 heading uppercase tracking-wide">
                  Recent
                </div>
                <div className="text-sm text-neutral-500 body">
                  No recent files
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default CodeEditor;
