import { useState } from "react";
import { motion } from "framer-motion";
import {
  FiZap,
  FiCode,
  FiSettings,
  FiDownload,
  FiCopy,
  FiLoader,
  FiCheck,
} from "react-icons/fi";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";

// Helper function to determine language from generator type
const getLanguageFromGenerator = (generatorType) => {
  const languageMap = {
    dockerfile: "dockerfile",
    "docker-compose": "yaml",
    kubernetes: "yaml",
    terraform: "hcl",
    "github-actions": "yaml",
    "azure-pipelines": "yaml",
    jenkins: "groovy",
    bash: "bash",
    powershell: "powershell",
  };

  return languageMap[generatorType] || "text";
};

const GenerationPanel = ({ workspace, setWorkspace }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  // Get active generator and settings from workspace
  const activeGenerator = workspace?.activeTemplate || "dockerfile";
  const settings = workspace?.settings || {};
  const generatedContent = workspace?.generatedCode?.content || null;
  const history = workspace?.history || [];

  // Sample configurations for different generators
  const sampleConfigs = {
    dockerfile: `# Multi-stage Node.js Dockerfile
# Generated by Deployio AI

    <>
      <SEO page="playground-generation" />
      <div className="h-full flex flex-col bg-neutral-900">
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:18-alpine AS build
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN npm run build

FROM node:18-alpine AS runtime
RUN addgroup -g 1001 -S nodejs
RUN adduser -S deployio -u 1001
WORKDIR /app
COPY --from=build --chown=deployio:nodejs /app/dist ./dist
COPY --from=dependencies --chown=deployio:nodejs /app/node_modules ./node_modules
COPY --chown=deployio:nodejs package*.json ./

USER deployio
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:3000/health || exit 1

CMD ["npm", "start"]`,

    "docker-compose": `version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@postgres:5432/deployio
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: deployio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:`,

    kubernetes: `apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployio-app
  labels:
    app: deployio-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployio-app
  template:
    metadata:
      labels:
        app: deployio-app
    spec:
      containers:
      - name: app
        image: deployio-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: deployio-app-service
spec:
  selector:
    app: deployio-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer`,

    terraform: `# Terraform Infrastructure Configuration
# Generated by Deployio AI

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# Variables
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "production"
}

# VPC
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "\${var.environment}-vpc"
    Environment = var.environment
  }
}

# Internet Gateway
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name        = "\${var.environment}-igw"
    Environment = var.environment
  }
}

# ECS Cluster
resource "aws_ecs_cluster" "main" {
  name = "\${var.environment}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = {
    Environment = var.environment
  }
}`,

    "github-actions": `name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: \${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linting
      run: npm run lint

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: \${{ env.REGISTRY }}
        username: \${{ github.actor }}
        password: \${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:latest`,
  };

  const handleGenerate = async () => {
    setIsGenerating(true);

    // Simulate AI generation process
    setTimeout(() => {
      const content = sampleConfigs[activeGenerator];

      // Update workspace with generated content
      if (setWorkspace) {
        setWorkspace({
          generatedCode: {
            type: activeGenerator,
            content: content,
            timestamp: new Date().toISOString(),
          },
          history: [
            ...history,
            {
              type: activeGenerator,
              settings,
              timestamp: new Date().toISOString(),
            },
          ],
        });
      }

      setIsGenerating(false);
    }, 2000);
  };

  const copyToClipboard = async (content) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const downloadFile = (content, filename) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getFileName = (type) => {
    const names = {
      dockerfile: "Dockerfile",
      "docker-compose": "docker-compose.yml",
      kubernetes: "deployment.yaml",
      terraform: "main.tf",
      "github-actions": "ci-cd.yml",
    };
    return names[type] || `${type}.txt`;
  };

  return (
    <div className="h-full flex flex-col bg-neutral-900">
      {/* Header */}
      <div className="p-6 border-b border-neutral-800/50 flex-shrink-0">
        <div className="flex items-center gap-3 mb-4">
          <FiZap className="w-6 h-6 text-yellow-400" />
          <div>
            <h2 className="text-2xl font-bold text-white heading">
              AI Configuration Generator
            </h2>
            <p className="text-neutral-400 body">
              Generate deployment configurations with AI assistance
            </p>
          </div>
        </div>
      </div>

      {/* Content - Scrollable */}
      <div
        className="flex-1 overflow-auto"
        style={{
          scrollbarWidth: "thin",
          scrollbarColor: "#525252 #262626",
        }}
      >
        <div className="p-6">
          {/* Generate Button */}
          <div className="mb-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-white heading mb-1">
                  {activeGenerator
                    .split("-")
                    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                    .join(" ")}{" "}
                  Generator
                </h3>
                <p className="text-sm text-neutral-400 body">
                  Generate optimized configuration for your deployment
                </p>
              </div>

              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={handleGenerate}
                disabled={isGenerating}
                className="flex items-center gap-2 px-6 py-3 bg-yellow-500/20 border border-yellow-500/30 rounded-lg text-yellow-400 hover:bg-yellow-500/30 transition-colors disabled:opacity-50 body"
              >
                {isGenerating ? (
                  <>
                    <FiLoader className="w-4 h-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <FiZap className="w-4 h-4" />
                    Generate Configuration
                  </>
                )}
              </motion.button>
            </div>
          </div>

          {/* Generated Configuration or Fallback */}
          <div
            className="bg-neutral-900/50 backdrop-blur-md border border-neutral-800/50 rounded-xl overflow-hidden"
            style={{ minHeight: "400px" }}
          >
            {generatedContent ? (
              <>
                {/* Code Header */}
                <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-800/50 flex-shrink-0">
                  <div className="flex items-center gap-2">
                    <FiCheck className="w-4 h-4 text-green-400" />
                    <span className="text-sm font-medium text-white heading">
                      Generated: {getFileName(activeGenerator)}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => copyToClipboard(generatedContent)}
                      className="p-1.5 rounded hover:bg-neutral-800 transition-colors text-neutral-400 hover:text-white"
                      title="Copy to Clipboard"
                    >
                      {copySuccess ? (
                        <FiCheck className="w-3.5 h-3.5 text-green-400" />
                      ) : (
                        <FiCopy className="w-3.5 h-3.5" />
                      )}
                    </motion.button>

                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() =>
                        downloadFile(
                          generatedContent,
                          getFileName(activeGenerator)
                        )
                      }
                      className="p-1.5 rounded hover:bg-neutral-800 transition-colors text-neutral-400 hover:text-white"
                      title="Download File"
                    >
                      <FiDownload className="w-3.5 h-3.5" />
                    </motion.button>
                  </div>
                </div>

                {/* Code Content */}
                <div
                  className="overflow-auto"
                  style={{
                    scrollbarWidth: "thin",
                    scrollbarColor: "#525252 #262626",
                    maxHeight: "400px",
                  }}
                >
                  <SyntaxHighlighter
                    language={getLanguageFromGenerator(activeGenerator)}
                    style={vscDarkPlus}
                    customStyle={{
                      margin: 0,
                      padding: "1rem",
                      background: "transparent",
                      fontSize: "0.875rem",
                      lineHeight: "1.5",
                      fontFamily:
                        'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
                    }}
                    wrapLines={true}
                    wrapLongLines={true}
                    showLineNumbers={true}
                    lineNumberStyle={{
                      color: "#6b7280",
                      paddingRight: "1rem",
                      fontSize: "0.75rem",
                    }}
                  >
                    {generatedContent}
                  </SyntaxHighlighter>
                </div>
              </>
            ) : (
              // Fallback content when no configuration is generated
              <div className="flex-1 flex items-center justify-center p-8">
                <div className="text-center max-w-md">
                  <FiCode className="w-16 h-16 text-neutral-600 mx-auto mb-4" />
                  <h3 className="text-lg font-semibold text-white mb-2 heading">
                    Ready to Generate
                  </h3>
                  <p className="text-neutral-400 body mb-6">
                    Configure your generation settings in the sidebar and click
                    &quot;Generate Configuration&quot; to create optimized
                    deployment files.
                  </p>
                  <div className="grid grid-cols-2 gap-4 text-xs">
                    <div className="bg-neutral-800/50 rounded-lg p-3">
                      <FiSettings className="w-4 h-4 text-blue-400 mb-2" />
                      <div className="text-neutral-300 font-medium mb-1">
                        Customizable
                      </div>
                      <div className="text-neutral-500">
                        Adjust settings in sidebar
                      </div>
                    </div>
                    <div className="bg-neutral-800/50 rounded-lg p-3">
                      <FiZap className="w-4 h-4 text-yellow-400 mb-2" />
                      <div className="text-neutral-300 font-medium mb-1">
                        AI-Powered
                      </div>
                      <div className="text-neutral-500">
                        Optimized configurations
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Generation History */}
          {history.length > 0 && (
            <div className="mt-4 flex-shrink-0">
              <div className="text-sm text-neutral-400 mb-2 body">
                Recent Generations
              </div>
              <div className="flex gap-2 overflow-x-auto">
                {history.slice(-5).map((item, index) => (
                  <motion.div
                    key={index}
                    whileHover={{ scale: 1.02 }}
                    className="flex-shrink-0 bg-neutral-800/50 rounded-lg px-3 py-2 cursor-pointer"
                    onClick={() => {
                      if (setWorkspace) {
                        setWorkspace({
                          activeTemplate: item.type,
                          generatedCode: null, // Clear previous generation
                        });
                      }
                    }}
                  >
                    <div className="text-xs text-neutral-300 font-medium">
                      {item.type
                        .split("-")
                        .map(
                          (word) => word.charAt(0).toUpperCase() + word.slice(1)
                        )
                        .join(" ")}
                    </div>
                    <div className="text-xs text-neutral-500">
                      {new Date(item.timestamp).toLocaleDateString()}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default GenerationPanel;
