import { useState } from "react";
import { motion } from "framer-motion";
import {
  FiZap,
  FiCode,
  FiPackage,
  FiSettings,
  FiDownload,
  FiPlay,
  FiCopy,
  FiLoader,
  FiCheck,
} from "react-icons/fi";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";

// Helper function to determine language from generator type
const getLanguageFromGenerator = (generatorType) => {
  const languageMap = {
    dockerfile: "dockerfile",
    "docker-compose": "yaml",
    kubernetes: "yaml",
    terraform: "hcl",
    "github-actions": "yaml",
    "azure-pipelines": "yaml",
    jenkins: "groovy",
    bash: "bash",
    powershell: "powershell",
  };

  return languageMap[generatorType] || "text";
};

const GenerationPanel = () => {
  const [activeGenerator, setActiveGenerator] = useState("dockerfile");
  const [isGenerating, setIsGenerating] = useState(false);

  const generators = [
    {
      id: "dockerfile",
      label: "Dockerfile",
      icon: FiPackage,
      description: "Generate optimized Dockerfile for your application",
      color: "blue",
    },
    {
      id: "docker-compose",
      label: "Docker Compose",
      icon: FiCode,
      description: "Create multi-service composition files",
      color: "green",
    },
    {
      id: "ci-cd",
      label: "CI/CD Pipeline",
      icon: FiPlay,
      description: "GitHub Actions workflow configuration",
      color: "purple",
    },
    {
      id: "terraform",
      label: "Terraform",
      icon: FiSettings,
      description: "Infrastructure as Code templates",
      color: "orange",
    },
  ];

  const sampleConfigs = {
    dockerfile: `# Multi-stage Node.js Dockerfile
# Generated by Deployio AI

FROM node:18-alpine AS dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:18-alpine AS build
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN npm run build

FROM node:18-alpine AS runtime
RUN addgroup -g 1001 -S nodejs
RUN adduser -S deployio -u 1001
WORKDIR /app
COPY --from=build --chown=deployio:nodejs /app/dist ./dist
COPY --from=dependencies --chown=deployio:nodejs /app/node_modules ./node_modules
COPY --chown=deployio:nodejs package*.json ./

USER deployio
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:3000/health || exit 1

CMD ["npm", "start"]`,

    "docker-compose": `# Docker Compose Configuration
# Generated by Deployio AI

version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@postgres:5432/deployio
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: deployio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:`,

    "ci-cd": `# GitHub Actions CI/CD Pipeline
# Generated by Deployio AI

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: \${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Run linting
        run: npm run lint

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: \${{ env.REGISTRY }}
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:latest`,

    terraform: `# Terraform Infrastructure Configuration
# Generated by Deployio AI

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# Variables
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "production"
}

# VPC
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "\${var.environment}-vpc"
    Environment = var.environment
  }
}

# Internet Gateway
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name        = "\${var.environment}-igw"
    Environment = var.environment
  }
}

# ECS Cluster
resource "aws_ecs_cluster" "main" {
  name = "\${var.environment}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = {
    Environment = var.environment
  }
}`,
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    // Simulate generation
    setTimeout(() => {
      setIsGenerating(false);
    }, 2000);
  };

  const copyToClipboard = (content) => {
    navigator.clipboard.writeText(content);
  };

  const downloadFile = (content, filename) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const activeGeneratorData = generators.find((g) => g.id === activeGenerator);
  const generatedContent = sampleConfigs[activeGenerator];

  return (
    <div className="h-full flex flex-col bg-neutral-900">
      {/* Header */}
      <div className="p-6 border-b border-neutral-800/50">
        <div className="flex items-center gap-3 mb-4">
          <FiZap className="w-6 h-6 text-yellow-400" />
          <div>
            <h2 className="text-2xl font-bold text-white heading">
              AI Configuration Generator
            </h2>
            <p className="text-neutral-400 body">
              Generate deployment configurations with AI assistance
            </p>
          </div>
        </div>

        {/* Generator Selection */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {generators.map((generator) => {
            const Icon = generator.icon;
            return (
              <motion.button
                key={generator.id}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => setActiveGenerator(generator.id)}
                className={`p-4 rounded-xl border transition-all text-left ${
                  activeGenerator === generator.id
                    ? `bg-${generator.color}-500/20 border-${generator.color}-500/30 text-${generator.color}-400`
                    : "bg-neutral-900/50 border-neutral-800/50 text-neutral-400 hover:border-neutral-700/50"
                }`}
              >
                <Icon className="w-6 h-6 mb-2" />
                <div className="text-sm font-semibold mb-1 heading">
                  {generator.label}
                </div>
                <div className="text-xs text-neutral-500 body">
                  {generator.description}
                </div>
              </motion.button>
            );
          })}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col p-6">
        {/* Active Generator Info */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <activeGeneratorData.icon
                className={`w-5 h-5 text-${activeGeneratorData.color}-400`}
              />
              <div>
                <h3 className="text-lg font-semibold text-white heading">
                  {activeGeneratorData.label}
                </h3>
                <p className="text-sm text-neutral-400 body">
                  {activeGeneratorData.description}
                </p>
              </div>
            </div>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleGenerate}
              disabled={isGenerating}
              className={`flex items-center gap-2 px-4 py-2 bg-${activeGeneratorData.color}-500/20 border border-${activeGeneratorData.color}-500/30 rounded-lg text-${activeGeneratorData.color}-400 hover:bg-${activeGeneratorData.color}-500/30 transition-colors disabled:opacity-50 body`}
            >
              {isGenerating ? (
                <>
                  <FiLoader className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <FiZap className="w-4 h-4" />
                  Generate
                </>
              )}
            </motion.button>
          </div>
        </div>

        {/* Generated Configuration */}
        <div className="flex-1 bg-neutral-900/50 backdrop-blur-md border border-neutral-800/50 rounded-xl overflow-hidden">
          {/* Code Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-800/50">
            <div className="flex items-center gap-2">
              <FiCheck className="w-4 h-4 text-green-400" />
              <span className="text-sm font-medium text-white heading">
                Generated Configuration
              </span>
            </div>

            <div className="flex items-center gap-2">
              <motion.button
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                onClick={() => copyToClipboard(generatedContent)}
                className="p-1.5 rounded hover:bg-neutral-800 transition-colors text-neutral-400 hover:text-white"
                title="Copy to Clipboard"
              >
                <FiCopy className="w-3.5 h-3.5" />
              </motion.button>

              <motion.button
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                onClick={() =>
                  downloadFile(
                    generatedContent,
                    `${activeGenerator}.${
                      activeGenerator === "docker-compose"
                        ? "yml"
                        : activeGenerator === "terraform"
                        ? "tf"
                        : activeGenerator === "ci-cd"
                        ? "yml"
                        : ""
                    }`
                  )
                }
                className="p-1.5 rounded hover:bg-neutral-800 transition-colors text-neutral-400 hover:text-white"
                title="Download File"
              >
                <FiDownload className="w-3.5 h-3.5" />
              </motion.button>
            </div>
          </div>

          {/* Code Content */}
          <div className="h-full overflow-auto custom-scrollbar">
            <SyntaxHighlighter
              language={getLanguageFromGenerator(activeGenerator)}
              style={vscDarkPlus}
              customStyle={{
                margin: 0,
                padding: "1rem",
                background: "transparent",
                fontSize: "0.875rem",
                lineHeight: "1.5",
                fontFamily:
                  'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
              }}
              wrapLines={true}
              wrapLongLines={true}
              showLineNumbers={true}
              lineNumberStyle={{
                color: "#6b7280",
                paddingRight: "1rem",
                fontSize: "0.75rem",
              }}
            >
              {generatedContent}
            </SyntaxHighlighter>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GenerationPanel;
